version: "3.7"

services:
  dstserver:
    image: derektamsen/dont-starve-together-server:latest
    build: .
    ports:
      - "10999:10999/udp"
    volumes:
      - dstconfig:/dstserver/dstserver_config

volumes:
  dstconfig:
