#!/usr/bin/env sh

cat << EOF > '/dstserver/dstserver_config/Cluster_1/Master/server.ini'
[network]
default_server_name = ${DST_DEFAULT_SERVER_NAME}
default_server_description = ${DST_DEFAULT_SERVER_DESCRIPTION}
server_port = ${DST_SERVER_PORT}
server_password = ${DST_SERVER_PASSWORD}
max_players = ${DST_MAX_PLAYERS}
pvp = ${DST_PVP}
game_mode = ${DST_GAME_MODE}
server_intention = ${DST_SERVER_INTENTION}
enable_snapshots = ${DST_ENABLE_SNAPSHOTS}
enable_autosaver = ${DST_ENABLE_AUTOSAVER}
tick_rate = ${DST_TICK_RATE}
connection_timeout = ${DST_CONNECTION_TIMEOUT}
server_save_slot = ${DST_SERVER_SAVE_SLOT}
vote_kick_enabled = ${DST_VOTE_KICK_ENABLED}
pause_when_empty = ${DST_PAUSE_WHEN_EMPTY}

[account]
dedicated_lan_server = ${DST_DEDICATED_LAN_SERVER}
EOF

cat << EOF > '/dstserver/dstserver_config/Cluster_1/Master/cluster_token.txt'
${DST_CLUSTER_TOKEN}
EOF

# Start Don't Starve Together Server
/dstserver/bin/dontstarve_dedicated_server_nullrenderer \
  -persistent_storage_root /dstserver \
  -conf_dir dstserver_config
